language: php

matrix:
    include:
        - php: 5.4
        - php: 5.5
        - php: 5.6
        - php: 7.0
        - php: 7.1
        - php: hhvm
    allow_failures:
        - php: 7.0
        - php: 7.1
        - php: hhvm

script:
    - phpunit --coverage-clover=coverage.clover

before_script:
    - composer install
    - mysql -uroot -e 'CREATE DATABASE spoon_tests'
    - mysql -uroot -e "CREATE USER 'spoon'@'localhost' IDENTIFIED BY 'spoon'"
    - mysql -uroot -e "GRANT ALL PRIVILEGES ON spoon_tests.* TO 'spoon'@'localhost'"
    - mysql -uroot -e 'FLUSH PRIVILEGES'

after_success:
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]] && [[ "$TRAVIS_PHP_VERSION" != "7" ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]] && [[ "$TRAVIS_PHP_VERSION" != "7" ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi

sudo: false
